shallow_clone: false

environment:
  matrix:
  - COMPILER: MSVC_16
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#  - COMPILER: MSVC_16
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build:
  verbosity: detailed
  parallel: true

cache:
  - c:\tools\vcpkg\installed\
  - c:\tools\vcpkg\downloads\

install:
  - cmd: cd C:\Tools\vcpkg
  - cmd: .\bootstrap-vcpkg.bat -disableMetrics
  - cmd: vcpkg.exe integrate install
  - cmd: vcpkg.exe install --triplet x86-windows-static sqlite3
  - cmd: mklink /D /J C:\projects\zeloengine\ThirdParty\Vcpkg c:\tools\vcpkg\

before_build:
  - cmd: cd C:\projects\zeloengine
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64
#  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x64 -host_arch=x64

build_script:
  - cmd: mkdir build_vs2019
  - cmd: cd build_vs2019
  - cmd: cmake -DCMAKE_GENERATOR_PLATFORM=win32 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G  "Visual Studio 16" ..
  - cmd: cmake --build . --config debug -j 18
